[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
testprogram = "4MJWw1fXkwcxmcvZYgXuAMvLdUaywEF4Y2ZYGkw8f4ZF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\ABHISHEK SWAMI\.config/solana/id.json'

[scripts]
test = "node tests/testprogram.js"
